### ISSUE TITLE
Upgrade intl to 0.19.0

### ISSUE THREAD

**Issue by lkevenson** [MohamedAbd0/time_slot#3]
**Because time_slot <0.0.2 depends on intl ^0.18.0 and time_slot >=0.0.2 <0.0.3 depends on intl ^0.17.0, time_slot <0.0.3 requires intl ^0.17.0 or ^0.18.0.
And because time_slot >=0.0.3 depends on intl ^0.18.0, every version of time_slot requires intl ^0.17.0 or >=0.18.0 <0.19.0.**

The intl has a new version so we get this error when we try to use the time_slot package.

Best regard,

**Comment by MohamedAbd0** [comment]
it is done and I upload new version time_slot: ^1.0.0
